// Copyright (c) 2023 Xu Shaohua <shaohua@biofan.org>. All rights reserved.
// Use of this source is governed by Apache-2.0 License that can be found
// in the LICENSE file.

type TokenVal = &'static str;

pub struct ColorTokens {
    pub neutral_foreground1: TokenVal,
    pub neutral_foreground1_hover: TokenVal,
    pub neutral_foreground1_pressed: TokenVal,
    pub neutral_foreground1_selected: TokenVal,
    pub neutral_foreground2: TokenVal,
    pub neutral_foreground2_hover: TokenVal,
    pub neutral_foreground2_pressed: TokenVal,
    pub neutral_foreground2_selected: TokenVal,
    pub neutral_foreground2_brand_hover: TokenVal,
    pub neutral_foreground2_brand_pressed: TokenVal,
    pub neutral_foreground2_brand_selected: TokenVal,
    pub neutral_foreground3: TokenVal,
    pub neutral_foreground3_hover: TokenVal,
    pub neutral_foreground3_pressed: TokenVal,
    pub neutral_foreground3_selected: TokenVal,
    pub neutral_foreground3_brand_hover: TokenVal,
    pub neutral_foreground3_brand_pressed: TokenVal,
    pub neutral_foreground3_brand_selected: TokenVal,
    pub neutral_foreground4: TokenVal,
    pub neutral_foreground_disabled: TokenVal,
    pub neutral_foreground_inverted_disabled: TokenVal,
    pub brand_foreground_link: TokenVal,
    pub brand_foreground_link_hover: TokenVal,
    pub brand_foreground_link_pressed: TokenVal,
    pub brand_foreground_link_selected: TokenVal,
    pub neutral_foreground2_link: TokenVal,
    pub neutral_foreground2_link_hover: TokenVal,
    pub neutral_foreground2_link_pressed: TokenVal,
    pub neutral_foreground2_link_selected: TokenVal,
    pub compound_brand_foreground1: TokenVal,
    pub compound_brand_foreground1_hover: TokenVal,
    pub compound_brand_foreground1_pressed: TokenVal,
    pub brand_foreground1: TokenVal,
    pub brand_foreground2: TokenVal,
    pub neutral_foreground1_static: TokenVal,
    pub neutral_foreground_inverted: TokenVal,
    pub neutral_foreground_inverted_hover: TokenVal,
    pub neutral_foreground_inverted_pressed: TokenVal,
    pub neutral_foreground_inverted_selected: TokenVal,
    pub neutral_foreground_inverted2: TokenVal,
    pub neutral_foreground_on_brand: TokenVal,
    pub neutral_foreground_static_inverted: TokenVal,
    pub neutral_foreground_inverted_link: TokenVal,
    pub neutral_foreground_inverted_link_hover: TokenVal,
    pub neutral_foreground_inverted_link_pressed: TokenVal,
    pub neutral_foreground_inverted_link_selected: TokenVal,
    pub brand_foreground_inverted: TokenVal,
    pub brand_foreground_inverted_hover: TokenVal,
    pub brand_foreground_inverted_pressed: TokenVal,
    pub brand_foreground_on_light: TokenVal,
    pub brand_foreground_on_light_hover: TokenVal,
    pub brand_foreground_on_light_pressed: TokenVal,
    pub brand_foreground_on_light_selected: TokenVal,
    pub neutral_background1: TokenVal,
    pub neutral_background1_hover: TokenVal,
    pub neutral_background1_pressed: TokenVal,
    pub neutral_background1_selected: TokenVal,
    pub neutral_background2: TokenVal,
    pub neutral_background2_hover: TokenVal,
    pub neutral_background2_pressed: TokenVal,
    pub neutral_background2_selected: TokenVal,
    pub neutral_background3: TokenVal,
    pub neutral_background3_hover: TokenVal,
    pub neutral_background3_pressed: TokenVal,
    pub neutral_background3_selected: TokenVal,
    pub neutral_background4: TokenVal,
    pub neutral_background4_hover: TokenVal,
    pub neutral_background4_pressed: TokenVal,
    pub neutral_background4_selected: TokenVal,
    pub neutral_background5: TokenVal,
    pub neutral_background5_hover: TokenVal,
    pub neutral_background5_pressed: TokenVal,
    pub neutral_background5_selected: TokenVal,
    pub neutral_background6: TokenVal,
    pub neutral_background_inverted: TokenVal,
    pub neutral_background_static: TokenVal,
    pub neutral_background_alpha: TokenVal,
    pub neutral_background_alpha2: TokenVal,
    pub subtle_background: TokenVal,
    pub subtle_background_hover: TokenVal,
    pub subtle_background_pressed: TokenVal,
    pub subtle_background_selected: TokenVal,
    pub subtle_background_light_alpha_hover: TokenVal,
    pub subtle_background_light_alpha_pressed: TokenVal,
    pub subtle_background_light_alpha_selected: TokenVal,
    pub subtle_background_inverted: TokenVal,
    pub subtle_background_inverted_hover: TokenVal,
    pub subtle_background_inverted_pressed: TokenVal,
    pub subtle_background_inverted_selected: TokenVal,
    pub transparent_background: TokenVal,
    pub transparent_background_hover: TokenVal,
    pub transparent_background_pressed: TokenVal,
    pub transparent_background_selected: TokenVal,
    pub neutral_background_disabled: TokenVal,
    pub neutral_background_inverted_disabled: TokenVal,
    pub neutral_stencil1: TokenVal,
    pub neutral_stencil2: TokenVal,
    pub neutral_stencil1_alpha: TokenVal,
    pub neutral_stencil2_alpha: TokenVal,
    pub background_overlay: TokenVal,
    pub scrollbar_overlay: TokenVal,
    pub brand_background: TokenVal,
    pub brand_background_hover: TokenVal,
    pub brand_background_pressed: TokenVal,
    pub brand_background_selected: TokenVal,
    pub compound_brand_background: TokenVal,
    pub compound_brand_background_hover: TokenVal,
    pub compound_brand_background_pressed: TokenVal,
    pub brand_background_static: TokenVal,
    pub brand_background2: TokenVal,
    pub brand_background_inverted: TokenVal,
    pub brand_background_inverted_hover: TokenVal,
    pub brand_background_inverted_pressed: TokenVal,
    pub brand_background_inverted_selected: TokenVal,
    pub neutral_stroke_accessible: TokenVal,
    pub neutral_stroke_accessible_hover: TokenVal,
    pub neutral_stroke_accessible_pressed: TokenVal,
    pub neutral_stroke_accessible_selected: TokenVal,
    pub neutral_stroke1: TokenVal,
    pub neutral_stroke1_hover: TokenVal,
    pub neutral_stroke1_pressed: TokenVal,
    pub neutral_stroke1_selected: TokenVal,
    pub neutral_stroke2: TokenVal,
    pub neutral_stroke3: TokenVal,
    pub neutral_stroke_on_brand: TokenVal,
    pub neutral_stroke_on_brand2: TokenVal,
    pub neutral_stroke_on_brand2_hover: TokenVal,
    pub neutral_stroke_on_brand2_pressed: TokenVal,
    pub neutral_stroke_on_brand2_selected: TokenVal,
    pub brand_stroke1: TokenVal,
    pub brand_stroke2: TokenVal,
    pub compound_brand_stroke: TokenVal,
    pub compound_brand_stroke_hover: TokenVal,
    pub compound_brand_stroke_pressed: TokenVal,
    pub neutral_stroke_disabled: TokenVal,
    pub neutral_stroke_inverted_disabled: TokenVal,
    pub transparent_stroke: TokenVal,
    pub transparent_stroke_interactive: TokenVal,
    pub transparent_stroke_disabled: TokenVal,
    pub neutral_stroke_alpha: TokenVal,
    pub stroke_focus1: TokenVal,
    pub stroke_focus2: TokenVal,
    pub neutral_shadow_ambient: TokenVal,
    pub neutral_shadow_key: TokenVal,
    pub neutral_shadow_ambient_lighter: TokenVal,
    pub neutral_shadow_key_lighter: TokenVal,
    pub neutral_shadow_ambient_darker: TokenVal,
    pub neutral_shadow_key_darker: TokenVal,
    pub brand_shadow_ambient: TokenVal,
    pub brand_shadow_key: TokenVal,
}

pub struct BrandVariants {
    pub b10: TokenVal,
    pub b20: TokenVal,
    pub b30: TokenVal,
    pub b40: TokenVal,
    pub b50: TokenVal,
    pub b60: TokenVal,
    pub b70: TokenVal,
    pub b80: TokenVal,
    pub b90: TokenVal,
    pub b100: TokenVal,
    pub b110: TokenVal,
    pub b120: TokenVal,
    pub b130: TokenVal,
    pub b140: TokenVal,
    pub b150: TokenVal,
    pub b160: TokenVal,
}

pub struct FontSizeTokens {
    pub s100: TokenVal,
    pub s200: TokenVal,
    pub s300: TokenVal,
    pub s400: TokenVal,
    pub s500: TokenVal,
    pub s600: TokenVal,
    pub s700: TokenVal,
    pub s800: TokenVal,
    pub s900: TokenVal,
    pub s1000: TokenVal,
}

pub struct LineHeightTokens {
    pub h100: TokenVal,
    pub h200: TokenVal,
    pub h300: TokenVal,
    pub h400: TokenVal,
    pub h500: TokenVal,
    pub h600: TokenVal,

    pub h700: TokenVal,
    pub h800: TokenVal,
    pub h900: TokenVal,
    pub h1000: TokenVal,
}

pub struct FontWeightTokens {
    pub regular: i32,
    pub medium: i32,
    pub semi_bold: i32,
    pub bold: i32,
}

pub struct FontFamilyTokens {
    pub base: TokenVal,
    pub monospace: TokenVal,
    pub numeric: TokenVal,
}

pub enum TextAlignment {
    Inherit,
    Initial,
    Revert,
    Unset,
    Center,
    End,
    Start,
    Justify,
    Left,
    MatchParent,
    Right,
}

pub struct TextAlignments {
    pub start: TextAlignment,
    pub center: TextAlignment,
    pub end: TextAlignment,
    pub justify: TextAlignment,
}

pub struct TypographyStyle {
    pub font_family: TokenVal,
    pub font_size: TokenVal,
    pub font_weight: TokenVal,
    pub line_height: TokenVal,
}

pub struct TypographyStyles {
    pub body1: TypographyStyle,
    pub body1_strong: TypographyStyle,
    pub body1_stronger: TypographyStyle,
    pub body2: TypographyStyle,
    pub caption1: TypographyStyle,
    pub caption1_strong: TypographyStyle,
    pub caption1_stronger: TypographyStyle,
    pub caption2: TypographyStyle,
    pub caption2_strong: TypographyStyle,
    pub subtitle1: TypographyStyle,
    pub subtitle2: TypographyStyle,
    pub subtitle2_stronger: TypographyStyle,
    pub title1: TypographyStyle,
    pub title2: TypographyStyle,
    pub title3: TypographyStyle,
    pub large_title: TypographyStyle,
    pub display: TypographyStyle,
}

pub struct BorderRadiusTokens {
    pub none: TokenVal,
    pub small: TokenVal,
    pub medium: TokenVal,
    pub large: TokenVal,
    pub xlarge: TokenVal,
    pub circular: TokenVal,
}

pub struct StrokeWidthTokens {
    pub thin: TokenVal,
    pub thick: TokenVal,
    pub thicker: TokenVal,
    pub thickest: TokenVal,
}

pub struct SpacingTokens {
    pub none: TokenVal,
    pub xxs: TokenVal,
    pub xs: TokenVal,
    pub s_nudge: TokenVal,
    pub s: TokenVal,
    pub m_nudge: TokenVal,
    pub m: TokenVal,
    pub l: TokenVal,
    pub xl: TokenVal,
    pub xxl: TokenVal,
    pub xxxl: TokenVal,
}

pub struct HorizontalSpacingTokens {
    pub none: TokenVal,
    pub xxs: TokenVal,
    pub xs: TokenVal,
    pub s_nudge: TokenVal,
    pub s: TokenVal,
    pub m_nudge: TokenVal,
    pub m: TokenVal,
    pub l: TokenVal,
    pub xl: TokenVal,
    pub xxl: TokenVal,
    pub xxxl: TokenVal,
}

pub struct VerticalSpacingTokens {
    pub none: TokenVal,
    pub xxs: TokenVal,
    pub xs: TokenVal,
    pub s_nudge: TokenVal,
    pub s: TokenVal,
    pub m_nudge: TokenVal,
    pub m: TokenVal,
    pub l: TokenVal,
    pub xl: TokenVal,
    pub xxl: TokenVal,
    pub xxxl: TokenVal,
}

pub struct DurationTokens {
    pub ultra_fast: TokenVal,
    pub faster: TokenVal,
    pub fast: TokenVal,
    pub normal: TokenVal,
    pub slow: TokenVal,
    pub slower: TokenVal,
    pub ultra_slow: TokenVal,
}

pub struct CurveTokens {
    pub accelerate_max: TokenVal,
    pub accelerate_mid: TokenVal,
    pub accelerate_min: TokenVal,
    pub decelerate_max: TokenVal,
    pub decelerate_mid: TokenVal,
    pub decelerate_min: TokenVal,
    pub easy_ease_max: TokenVal,
    pub easy_ease: TokenVal,
    pub linear: TokenVal,
}

pub struct ShadowTokens {
    pub s2: TokenVal,
    pub s4: TokenVal,
    pub s8: TokenVal,
    pub s16: TokenVal,
    pub s28: TokenVal,
    pub s64: TokenVal,
}

pub struct ShadowBrandTokens {
    pub s2: TokenVal,
    pub s4: TokenVal,
    pub s8: TokenVal,
    pub s16: TokenVal,
    pub s28: TokenVal,
    pub s64: TokenVal,
}
